export class Case {

  constructor(
    public id: number,
    public name: String,
    public status: String,
    public salesPersonName: String,
    public userId: String,
    public clientName: String,
    public corporateName: String,
    public location: String,
    public phone: String,
    public industry: String,
    public settlementMonth: String,
    public enrolledInsurance: String,
    public representativeName: String,
    public representativeNameCeo: String,
    public representativeBirthday: String,
    public representativePersonSex: String,

   public officerName: string [],
   public officerNickName: string [],
   public officierBirthday: string [],
   public offcierSex: string [],
   public officierPosition: string [],
   public officerRelationWithReprentative: string [], 

    /*public officerName: String,
    public officerNickName: String,
    public officierBirthday: String,
    public offcierSex: String,
    public officierPosition: String,
    public officerRelationWithReprentative: String,*/

    /*public officer2Name: String,
    public officer2NickName: String,
    public officier2Birthday: String,
    public offcier2Sex: String,
    public officier2Position: String,
    public officer2RelationWithReprentative: String,
    public officer3Name: String,
    public officer3NickName: String,
    public officier3Birthday: String,
    public offcier3Sex: String,
    public officier3Position: String,
    public officer3RelationWithReprentative: String,*/
    public advancedDisability: String,
    public obstaclesForManager: String,
    public gurranteeOfAdvancedDisaility: String,
    public successionFunds: String,
    public guaranteeingDeath: String,
    public insuranceClaim: String,
    public advancedDisabledSecurity: String,
    public insurancePremiums: String,
    public paymentProcedure: String,
    public healthyInsuranceCompany: String,
    public ExpensesSecurity: String,
    public insuranceForManager: String,
    public insuranceForEmployee: String,
    public diseases: String,
    public hospitalization: String,
    public cancer: String,
    public retirement: String,
    public payment: String,
    public individuals: String,
    public premiums: String,
    public insuranceForcompany: String,
    public nursingCare: String,
    public nursingCareManager: String,
    public nursingCareGuarantee: String,
    public insurancePayment: String,
    public goodsInsured: String,
    public nursingCareAfterRetirement: String,
    public cashInsurance: String,
    public nursinghealthyInsuranceCompany: String,
    public assetsWanted: String,
    public foreignCurrency: String) {
  }
}
